### PR TITLE
Samples add structural adapter etabs and modify revit file

### PR DESCRIPTION
**Pull request by enarhi**
Purged unused in the old revit file to eliminate unused families, data, etc and renamed to analysis instead of robot as it can be used for other analysis interop as well. Added an Etabs sample script similar to the Robot one. Further tweaks may be made to the Etabs sample script, and we may imperialize it to provide out of the box examples of interop for both unit systems.

### CODE REVIEW

**Comment by JosefTaylor** [comment]
Hmm, the pulls don't work for this guy. I just compiled the master branch of everything using Code Assistant- was this created in an earlier version?
[EDIT] there was a problem with my BHoM install, when I fixed it I was greeted with perfect functioning of this sample. Approved!

**Review by JosefTaylor — DISMISSED** [review]

**Review by IsakNaslundBh — CHANGES_REQUESTED** [review]
Some points, I have pushed changes for the following:

1. Think we should try to enforce best practice in these kind of sample scripts by having the adapters turned off in the scripts, by having the activate toggled to false.
1. Some of the collecting parameter stages of the scripts are bypassed, have rewired things to go through there
1. Added fix for wall support to the Robot sample script to mirror fix made for ETABS

Have not fixed the following:

After an update to the Revit_Toolkit here:  https://github.com/BHoM/Revit_Toolkit/pull/207, the Revit_Toolkit now properly pulls the assigned materials in the Revit model. The families in the example model does not have any materials assigned to them, leading to null materials on all sections. Can the families in the Revit model please be updated to link to proper standard materials?

**Comment by enarhi** [comment]
Alright, done fiddling about with this one, materials updated and tested. Using normal and lightweight concrete now to highlight variation in material and corresponding density tracking through to BHoM elements. @IsakNaslundBh , have a look and lets get this merged if it looks good on your end.

**Review by IsakNaslundBh — APPROVED** [review]

**Comment by IsakNaslundBh** [comment]
Had completely missed your comment here @enarhi !

Revit model seem to be fine now after your update. I updated the script to work with the new definition of nodes, now owning a coordinate system instead of a point. If one of you would like to quickly check through everything is still working on your end, we can then merge!

**Comment by enarhi** [comment]
@IsakNaslundBh looks good. @JosefTaylor , perhaps we include a base ETABS model with stories/grid loaded in to highlight the need to preload datum for ETABS? Might be worth a separate pull, lets get this one merged!

**Comment by IsakNaslundBh** [comment]
Thanks @enarhi

**Pull request merged**
