### PR TITLE
samples - Issue 23 - add sample file for live streaming of nurbs between Grasshopper and Dynamo

### LINKED ISSUE #23: Create Sample GH and DYN scripts to pass NurbsSurface via Sockets
This will be a good one to add to the samples repo now functionality is in latest Beta v2.3.β.0

### PR DESCRIPTION
**Pull request by epignatelli**
Closes #23 

I added a sample script to live streaming `NurbsSurface` between Dynamo and Grasshopper.
The script is pretty simple, because it aims at showing the procedure.

I added more reviewers than usual, since I think this is a pretty delicate one, and has to work.

*__My idea is to wait for all of you reviewers to approve, before merging.__*
*__If you think you cannot review, for any reason, feel free to remove yourself.__*

There are instructions in the files themselves. 
I won't add any more, so we can also test how clear are those.

As a note, this is one of the last bits to consider the 2.3.beta complete.

### CODE REVIEW

**Review by michaldengusiak — COMMENTED** [review]
I open in GH all fine
image

then Dynamo but it does not work for me
image

do I miss any step?

**Review by ZiolkowskiJakub — DISMISSED** [review]
It worked for me. BHoM NurbSurface pulled from Grashopper and pushed to Dynamo however I could not get any preview of NurbSurface.

**Comment by epignatelli** [comment]
> I open in GH all fine
> 
> then Dynamo but it does not work for me
> 
> do I miss any step?

This sample relies on the Dynamo PR that is going to be merged on Monday:
https://github.com/BHoM/Dynamo_Toolkit/pull/158

**Comment by epignatelli** [comment]
@michaldengusiak 
@rwemay 
@enarhi 
@pawelbaran 
https://github.com/BHoM/Dynamo_Toolkit/pull/158 is now on master, any news on testing this?

**Comment by michaldengusiak** [comment]
@epignatelli  

test1: open RevitDynamo, GH - approved
I run it once but could not  see anything so I change all to false then I changed port to next number `4142` in Dynamo and GH and then run `True` in GH and `True` in Dyanmo and works fine
image

test 2: open DynamoSandboc, GH - tbd
could not see BHoM in my DynamoSandbox... anyone have problems loading BHoM in dynamo sandbox on current master?

**Comment by epignatelli** [comment]
When I open Dynamo, and then I close it, the process remains alive in the background:
image

If you then try to rebuild the Dynamo_Toolkit, it will give no error. Although, post-build events actually fail silently. 
A workaround is to open the Task Manager, go to Details, look for the Dynamo process, kill it, and the rebuild the Dynamo_Toolkit.

**Comment by michaldengusiak** [comment]
yes, correct I already logged this some time ago https://github.com/BHoM/Dynamo_Toolkit/issues/140
I have all closed and rebuild. Issue is that opens fine with Revit and not with Dynamo Sandbox. Maybe we have some objects that are Revit related and therefore prevent DynamoSandbox from loading ?

I just delete Dynamo repo, delete BHoM from Dynamo packages and rebuild all again and still BHoM does not open for me in DynamoSandbox....

I just found more less issue and will log this under Dynamo..

**Review by michaldengusiak — APPROVED** [review]
@epignatelli I can not stop digging until got solution
so I identified issue with [DynamoSandbox](https://github.com/BHoM/Dynamo_Toolkit/issues/159) solve it for me locally and can continue test

so test2: approved
works fine under DynamoSandbox! huurey :)

image

**Comment by pawelbaran** [comment]
The sample works fine! One important observation: **Dynamo_Toolkit needs to be built first** because it does not update the assemblies in _%appdata%\BHoM\Asssemblies_ folder (does it only in its own directory), so if GH goes first, then we end up with pre-build .dll in BHoM assemblies and the latest build in the local Dynamo dir.


image

**Review by pawelbaran — APPROVED** [review]

**Review by al-fisher — APPROVED** [review]
This is also (seemingly) working for me (rendering issue has recurred for me though - so limited to interrogating Dynamo nodes).
But approving and will merge as good number have commented - thanks @epignatelli , all

**Pull request merged**
