### PR TITLE
samples: Closes Issue #17

### LINKED ISSUE #17: samples: : Update due to changes in Structures_oM
Update due to changes made in:

https://github.com/BHoM/BHoM/issues/464
https://github.com/BHoM/BHoM_Engine/issues/922

### PR DESCRIPTION
**Pull request by peterjamesnugent**
Closes #17 

Updates to all Grasshopper scripts in the following path:
samples\Structural_Adapters

The Dynamo script needs to be updated here:
samples\Structural_Adapters\Interop Revit ETabs Lusas Robot

- All custom objects reserialised 
- All components recreated where necessary
- Interop Revit script generalised and is now suitable for Etabs, Robot and Lusas

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
Do not merge label added to allow @IsakNaslundBh to make changes to the Dynamo script.

**Comment by peterjamesnugent** [comment]
@alexradne I have added you as a reviewer as Isak is now on leave.

**Comment by alelom** [comment]
@ZiolkowskiJakub could you please test the dynamo script please? I'm having trouble opening Dynamo.

**Comment by alelom** [comment]
## Summary of results
- `samples\Structural_Adapters\Elements` - no issues
- `samples\Structural_Adapters\Loads` - updated a component that was showing the `old` tag overlay; updated a component that was not working due to old instance
- `samples\Structural_Adapters\Properties` - no issues (@peterjamesnugent I have done these too)
- `samples\Structural_Adapters\Workflows` - no issues
- `samples\Structural_Adapters\Interop Revit ETabs Lusas Robot`:
   - In `BHoM Samples - Interop - Revit_Robot.gh` I'm getting the following error from the second Pull:
image
   - Consequently couldn't test the dynamo one -- would be good to have someone with a bit more experience on using that definition to test -- @ZiolkowskiJakub could you please test both scripts in this folder?
- `samples\Structural_Adapters\Lusas_Toolkit` - @peterjamesnugent to test.

**Comment by peterjamesnugent** [comment]
Verified all Lusas_Toolkit scripts by pushing to Lusas. 

I have removed reference to Lusas in the Revit Interop script because there are some properties Lusas does not currently support (i.e. Concrete Sections). I have also renamed the script and folder it is in so that it does list specific adapters.

**Comment by alelom** [comment]
> * `samples\Structural_Adapters\Interop Revit ETabs Lusas Robot`:
>   
>   * In `BHoM Samples - Interop - Revit_Robot.gh` I'm getting the following error from the second Pull:
>     image

@peterjamesnugent have you had a chance to see if you get this same error here?

**Comment by peterjamesnugent** [comment]
I am able to recreate that error but no impact on the push.

**Comment by peterjamesnugent** [comment]
@MartinHenriksen added to update the Dynamo script as discussed in the weekly structures call.

**Comment by peterjamesnugent** [comment]
Interop Revit script pushes completely to Robot.

**Comment by MartinHenriksen** [comment]
> @MartinHenriksen added to update the Dynamo script as discussed in the weekly structures call.

@peterjamesnugent the Dynamo script is updated but I had to change the adaptor from ETABS to a Robot one as I don't have access to ETABS atm

**Review by alelom — APPROVED** [review]
Thanks @epignatelli ! That removes the Warning from the Pull component, that was caused from the old Pull having an incorrect method call

**Comment by epignatelli** [comment]
@peterjamesnugent @alelom I just pushed a fix to the sample.
The `Pull` component was instantiated _before_ the batch-change of `Query` to `Request`.

**Pull request merged**
