### PR TITLE
adding grasshopper samples

### PR DESCRIPTION
**Pull request by rolyhudson**
Just adding Grasshopper sample files created for Theatron methods. Not too sure if the folder structure is excessive as there are so few samples

samples\Engine\Architecture_Engine\Theatron

### CODE REVIEW

**Comment by al-fisher** [comment]
Hey @rolyhudson - thanks for this! Great addition 
One thing these scripts have a "Mesh Face Cull" component from the plugin Toro! Are we able to upload versions of the script without this dependency? 
image
Thanks so much

**Review by al-fisher — CHANGES_REQUESTED** [review]
Remove plugin dependency as per comment. Thanks

**Comment by rolyhudson** [comment]
> Remove plugin dependency as per comment. Thanks

@al-fisher thanks for reviewing. The dependency is now removed. Cheers Roly

**Review by al-fisher — APPROVED** [review]

**Comment by al-fisher** [comment]
Perfect - thanks @rolyhudson

**Pull request merged**
