### PR TITLE
Structural Adapter

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### This PR has been archived 

Historic PR archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

### CODE REVIEW

**Comment by alexradne** [comment]
Looks good I think! I like the hello world message 😄 

Just a note, Panel Planar is used in some of the sample scripts, but they are not supported for GSA. GSA uses FEMeshes instead. But this might not be crucial. What do you think?

**Comment by peterjamesnugent** [comment]
@alexradne can you create a generic script for CreateFEMesh like we have for CreateBar? Users can then check the Wiki if the adapter supports it or not.

Can FEMesh objects be assigned to load properties such as AreaTemperatureLoad, AreaUniformlyDistributedLoad etc.? If that's the case it may be worth having a component with FEMesh objects to push in those scripts.

**Comment by alexradne** [comment]
I have added a create FEMesh script, but I found out that the AreaUniformlyDistributedLoad on FEMeshes is not implemented for GSA yet. So I will leave that for now

**Comment by JosefTaylor** [comment]
Great stuff. ETABS has a load of trouble getting through this, which is providing me ample fodder for development!

**Comment by JosefTaylor** [comment]
I did note a typo: in your comparison component you've misspelled "Original"

**Comment by peterjamesnugent** [comment]
Does anyone have any comments on the scripts? Going to merge in 30 minutes.

**Pull request merged**
