### PR TITLE
Create Pull Revit - Push gbXML_01.dyn

### LINKED ISSUE #6: samples: update gbXML samples to new structure
due to new implementation for XML sample file are added to reflect this change

ExportTypes
o	TAS – generic gbXML
o	IES – IES Specific Fixes
Export Details
o	BuildingShell 
o	Full
IndividualSpaces

### PR DESCRIPTION
**Pull request by michaldengusiak**
Fixes #6

### CODE REVIEW

**Review by mariatjader — DISMISSED** [review]
Some thoughts; 
Shall we change the panel linking to Michal's test folder to be empty or an example text? 

I am using the SAM Test model from Revit and am not pulling any shading elements. Maybe there just aren't any shading elements in the model (The GH script seems to works anyway and pulls and pushes data). 

In the previous script Pull Revit - Push gbXML.gh the XML adapter was old and had to be changed. But it might not matter as there is this new version of the test file.

**Comment by michaldengusiak** [comment]
@mariatjader  this is fine... I am referring to test location so it does not matter everyone will change directory path .. this is just indication

yes, these are just update same script to accommodate change with `ExportType and Detail`
all functionality issues we log under XML

**Comment by mariatjader** [comment]
Ok cool @michaldengusiak , no problem then :)

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
GH script (and probably Dynamo too) - the openings part is not correct as per our discussions when testing the XML Toolkit last week, can you update to the correct version to get openings?

Also, can you produce a sample script that uses the one-component option for people to see as well? :smile:

**Comment by michaldengusiak** [comment]
yes, I will add this too and load sample gbXML as discussed with Theo

**Comment by michaldengusiak** [comment]
@FraserGreenroyd  scripts updated and we have two options inside, please review again

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed and approved - great work!

**Pull request merged**
