### PR TITLE
Add Excel Pull from Revit Toolkit Sample

### PR DESCRIPTION
**Pull request by kayleighhoude**
image

### CODE REVIEW

**Review by pawelbaran — COMMENTED** [review]
I have just ran the script on the sample architecture file shipped with Revit 2018. Not sure if that is OK @kayleighhoude:

image

Btw, sorry for a possibly dumb question, but how should the .ini file be used? A 3-sentence readme file or a .gif could possibly be helpful (or, even better, the missing Excel-related parts of Revit_Toolkit wiki).

**Comment by kayleighhoude** [comment]
@pawelbaran agreed that the Revit Toolkit wiki should be updated with some Excel examples similar to the other UIs, with GIFs related to this sample file (ex: knowing the difference between space and room properties here being a key) Would we be ok pushing this sample in and updating the wiki later?

**Comment by pawelbaran** [comment]
Sure thing. However, is the ouptut I have shown in my previous comment correct? Room name and room number is zero for all pulled objects.

**Comment by FraserGreenroyd** [comment]
@kayleighhoude can we get an update on this please? :smile:

**Comment by FraserGreenroyd** [comment]
As no update has been provided and the code base has moved on since these samples were created, these are unlikely to be beneficial at this time, so I am closing this PR.

**Pull request closed without merging**
