### PR TITLE
Revit_Toolkit sample cleanup vol. 1

### PR DESCRIPTION
**Pull request by pawelbaran**
- C# sample updated to work on 3.1
- Others folder (dump of legacy BEnv scripts) deleted

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
I know there is a wider samples clean up occurring soon so am happy with the clean up of BEnv material for now as it still appears in history.

**Comment by michaldengusiak** [comment]
@pawelbaran  hi...I can see you are deleting some examples are you moving them to a different location ? or they do not work with current code?

**Comment by pawelbaran** [comment]
Hello from the other side @michaldengusiak! The scripts do not work (probably could be fixed with a few minor changes, same as @ZiolkowskiJakub's C# sample) - I just thought it will be easier to let the BEnv guys start from scratch and reuse whatever they like.

Reflecting on that again, I might have gone a step too far with deleting things. What do you think @FraserGreenroyd? My goal is to simply keep only scripts that work.

**Comment by FraserGreenroyd** [comment]
@pawelbaran I'm happy with what you did as per my review so happy for this to be merged as is.

**Comment by pawelbaran** [comment]
Right, let's do it then (I have no merge rights though).

**Pull request merged**
